# Generated by Django 3.2.6 on 2023-07-11 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no_1', models.CharField(max_length=50)),
                ('contact_no_2', models.CharField(max_length=50)),
                ('reg_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('pan_no', models.CharField(max_length=50)),
                ('gst_no', models.CharField(max_length=50)),
                ('iec_code', models.CharField(max_length=50)),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bank_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('acc_no', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('swift_code', models.CharField(max_length=50)),
                ('ad_code', models.CharField(max_length=50)),
                ('blank_cheque', models.ImageField(upload_to='')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
