# Generated by Django 3.2.6 on 2023-09-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_blank_cheque_bank_details_upload_blank_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='profile_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
