# Generated by Django 3.2.6 on 2023-09-11 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_alter_profile_picture_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='profile_image',
            field=models.ImageField(upload_to='logo'),
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.CharField(max_length=150)),
                ('q_date', models.CharField(max_length=150)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_address', models.CharField(max_length=150)),
                ('customer_contact', models.CharField(max_length=150)),
                ('customer_gst', models.CharField(max_length=150)),
                ('customer_reference', models.CharField(max_length=150)),
                ('remark', models.CharField(max_length=150)),
                ('totalAmount', models.CharField(max_length=150)),
                ('packingForwarding', models.CharField(max_length=150)),
                ('cgst', models.CharField(max_length=150)),
                ('cgst_total', models.CharField(max_length=150)),
                ('sgst', models.CharField(max_length=150)),
                ('sgst_total', models.CharField(max_length=150)),
                ('igst', models.CharField(max_length=150)),
                ('igst_total', models.CharField(max_length=150)),
                ('grand_total', models.CharField(max_length=150)),
                ('amt_in_words', models.CharField(max_length=150)),
                ('payment_tc', models.CharField(max_length=150)),
                ('delivery_time_tc', models.CharField(max_length=150)),
                ('pf_tc', models.CharField(max_length=150)),
                ('for_tc', models.CharField(max_length=150)),
                ('q_validity_tc', models.CharField(max_length=150)),
                ('moq_tc', models.CharField(max_length=150)),
                ('material_tc', models.CharField(max_length=150)),
                ('other_tc', models.CharField(max_length=150)),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=150)),
                ('item_details', models.CharField(max_length=150)),
                ('grade', models.CharField(max_length=150)),
                ('uom', models.CharField(max_length=150)),
                ('moq', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.quotation')),
            ],
        ),
    ]
