# Generated by Django 3.2.6 on 2023-09-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_quotation_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quotation',
            new_name='quotation_data',
        ),
    ]
