# Generated by Django 5.0.1 on 2024-02-09 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_quotation_quotation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quotation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.quotation_data'),
        ),
        migrations.AlterField(
            model_name='profile_picture',
            name='profile_image',
            field=models.ImageField(upload_to='logo/'),
        ),
    ]
