# Generated by Django 5.0.1 on 2024-02-09 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_item_quotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.quotation_data'),
        ),
    ]
