# Generated by Django 5.0.1 on 2024-02-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_item_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('joining_date', models.CharField(max_length=150)),
                ('salary', models.CharField(max_length=150)),
            ],
        ),
    ]
