# Generated by Django 5.0.1 on 2024-02-09 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_attendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employeedetails'),
        ),
    ]
