# Generated by Django 5.0.1 on 2024-03-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_attendancerecord_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
