# Generated by Django 5.0.1 on 2024-03-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_data',
            name='name',
        ),
    ]
