# Generated by Django 5.0.1 on 2024-03-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_quotation_data_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=150)),
                ('item_details', models.CharField(max_length=150)),
                ('grade', models.CharField(max_length=150)),
                ('uom', models.CharField(max_length=150)),
                ('moq', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.quotation_data')),
            ],
        ),
    ]
