# Generated by Django 5.0.1 on 2024-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quotation',
            field=models.CharField(max_length=150),
        ),
    ]
