# Generated by Django 5.0.1 on 2024-04-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_proforma_invoce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proforma_invoce',
            old_name='delivery_time_tc',
            new_name='PO_number',
        ),
        migrations.RenameField(
            model_name='proforma_invoce',
            old_name='for_tc',
            new_name='po_date',
        ),
        migrations.RemoveField(
            model_name='proforma_invoce',
            name='material_tc',
        ),
        migrations.RemoveField(
            model_name='proforma_invoce',
            name='moq_tc',
        ),
        migrations.RemoveField(
            model_name='proforma_invoce',
            name='other_tc',
        ),
        migrations.RemoveField(
            model_name='proforma_invoce',
            name='payment_tc',
        ),
        migrations.RemoveField(
            model_name='proforma_invoce',
            name='pf_tc',
        ),
        migrations.RemoveField(
            model_name='proforma_invoce',
            name='q_validity_tc',
        ),
    ]
