# Generated by Django 5.0.1 on 2024-04-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_tax_invoce'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half_Day', 'Half-Day')], max_length=10),
        ),
    ]
