# Generated by Django 5.0.1 on 2024-04-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_materialdetails_alter_attendancerecord_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_details',
            name='upload_blank_cheque',
        ),
    ]
