# Generated by Django 5.0.1 on 2024-04-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_bank_details_upload_blank_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetails',
            name='max_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialdetails',
            name='min_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
